### ISSUE TITLE
GUI glitches in high dpi

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#39]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/19374731/186107785-bd3985d1-4397-4cc9-8c90-6c0645d30970.png">

**Comment by falkTX** [comment]
which build is this? the brickwall going out of bounds is supposedly fixed now
the easy page should show the commit used to build it

**Comment by trummerschlunk** [comment]
it was cd340447 on macos

**Comment by falkTX** [comment]
yeah that is an old build. this was fixed in baedaf51010bae1e05bdae405058e553407a0c3f

the leveler gain label doesnt matter now since we are moving it

**Comment by trummerschlunk** [comment]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/19374731/186117442-3da35d5c-17e4-4570-a0e1-713ed78d2281.png">

kneecomp drywet still does not scale in high-dpi

Build: https://github.com/trummerschlunk/soundsgood/actions/runs/2910056448

**Comment by falkTX** [comment]
> kneecomp drywet still does not scale in high-dpi

fixed in ff753f654e3399d1d583c23fc6e0215b32d811aa

**Comment by falkTX** [comment]
these should all be fixed now, right?

**Comment by trummerschlunk** [comment]
fixed!
